/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData icon_metro_stethoscope = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_awesome_hands_helping = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats_icon_clicked = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
